program for fibonacci search
WebClub-NITK/Hacktoberfest-2k17 pull request #793
Opened 2017-10-31 10:26 UTC by lovish318

This Pull Request resolves Issue #19 

Description:
In this Pull Request we have done the following additions/edits for the code:

program for fibonacci search

2017-10-31 10:46 UTC, shyamdr commented
#include<iostream>
 
using namespace std;
 
void FibonacciSearch(int *a, int start, int end, int *fab, int index, int item)
{
	int i, mid;
 
	// Assigning middle of the array using Fibonacci element.
	mid = start+fab[index-2];
 
	// Return if item found at mid index.
	if(item == a[mid])
	{
		cout<<"\n item found at "<<mid<<" index.";
		return;
	}
	// Return if item found at start index.
	else if(item == a[start])
	{
		cout<<"\n item found at "<<start<<" index.";
		return;
	}
	// Return if item found at end index.
	else if(item == a[end])
	{
		cout<<"\n item found at "<<end<<" index.";
		return;
	}
	// If mid becomes start or end of the sub-array then element not found.
	else if(mid == start || mid == end)
	{
		cout<<"\nElement not found";
		return;
	}
	// According to the item value choose the partion to proceed further.
	else if(item > a[mid])
		FibonacciSearch(a, mid, end, fab, index-1, item);
	else
		FibonacciSearch(a, start, mid, fab, index-2, item);
}
 
main()
{
	int n, i, biter, fab[20], a[20]={1, 9, 18, 24, 27, 35, 38, 41, 49, 53, 55, 66, 67, 72, 75, 77, 81, 89, 90, 97};
	char ch;
 
	fab[0] = 0;
	fab[1] = 1;
	i = 1;
	while(fab[i] < 20)
	{
		i++;
		fab[i] = fab[i-1]+fab[i-2];
	}
 
	up:
	cout<<"\nEnter the Element to be searched: ";
	cin>>n;
 
	// Implement Fibonacci search.
	FibonacciSearch(a, 0, 19, fab, i, n);
 
	// Ask user to enter choice for further searching.
	cout<<"\n\n\tDo you want to search more...enter choice(y/n)?";
	cin>>ch;
	if(ch == 'y' || ch == 'Y')
		goto up;
 
	return 0;
}

2017-11-02 09:29 UTC, utkarsh23 commented
@shyamdr I'm not quite sure why you've commented whatever it is that you have commented. If you're looking to contribute to the repository, please create a pull request.

2017-11-02 09:30 UTC, utkarsh23 requested changes

2017-11-02 09:30 UTC, utkarsh23 commented on fibonacci_search/lovish318.c
> +    x = 30;
Please make provisions to accept the array as well the element to be search for, as an input from the user.

2017-11-03 09:45 UTC, salman-bhai commented
Are there any updates or should we close the PR?

2017-11-06 06:00 UTC, salman-bhai commented
PR closed due to inactivity

2017-11-06 06:00 UTC, closed without merging